INSERT INTO TvCountryTb (SeriesId, CountryId) VALUES 
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Стрела'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жизнь после людей'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Следующее поколение'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Санта-Хрякус'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Англия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одиссея 5'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В пустыне смерти'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Австралия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Война и мир'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5 - Затерянные сказания'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Узник'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уилфред'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новая Одиссея'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Выжившие'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Игра престолов'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агенты Щ.И.Т.'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город гангстеров'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Под куполом'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мастера научной фантастики'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Космические рейнджеры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джекил'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дракула'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Десница Божья'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новый день'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сотня'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джонатан Стрендж и мистер Норрелл'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агент Картер'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бойтесь ходячих мертвецов'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Компьютерщики'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Англия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Светлячок'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крайние меры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенды завтрашнего дня'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Падение'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Падение'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Нация Z'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Железный человек'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Каприка '), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сонная лощина'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Плащ'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Касл'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джессика Джонс'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черный список'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Войны клонов'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Обмани меня'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Франкенштейна'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На Тихом океане'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мотель Бейтса'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Орлиное сердце'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Колония'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Красавица и чудовище'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бульварные ужасы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бульварные ужасы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Ирландия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бульварные ужасы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Герои: Возрождение'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Искусственный интеллект'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Аквамен'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Фарт'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Избранный'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лучше звоните Солу'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '11.22.63'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Глубокий космос 9'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Забытые'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Константин'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Первородные'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Франция')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Германия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супершторм'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Острые козырьки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Почти человек'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Контакт'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Конец детства'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Салем'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притяжению вопреки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притяжению вопреки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Неизвестные'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флеминг: человек, который хотел стать Бондом'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во плоти'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уэйуорд Пайнс'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '2057: Канал Дискавери'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди будущего'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Фильмы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Врата'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Пропавшая комната'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Континуум'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Континуум'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доктор Хаус'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клан Кеннеди'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последний корабль'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ходячие мертвецы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вечность'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Космос: Далёкие уголки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Верь'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Слепое пятно'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Таинственные знаки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Франция')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Таинственные знаки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Бельгия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Таинственные знаки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Швейцария')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Киллджойс'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Готэм'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Демоны да Винчи'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тайный круг'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тайный круг'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Укушенная'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Темная материя'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спираль'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рождение мафии: Нью-Йорк'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Алькатрас'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Герои'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Фарго'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Подозреваемый'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мёртвые, как я'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мёртвые, как я'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во все тяжкие'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Восстание Техаса'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '4400'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шерлок'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Библиотекари'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терминатор: Хроники Сары Коннор'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Культ'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Барыги'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Быть человеком'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Быть человеком'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Области тьмы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Экспансия'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сошедшие с небес'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Батл Крик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Записки юного врача'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек в высоком замке'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Элементарно'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Секретные материалы'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Декстер'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Волшебники'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Оригинальный'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '12 обезьян'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Квантовый скачок'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клондайк'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клондайк'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Андромеда'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флэш'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Живая мишень'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Англия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ад на колесах'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ад на колесах'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ад на колесах'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ребенок Розмари'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Калифорникейшн'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остаться в живых'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Изгои'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гримм'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Управление гневом'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Викинги'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Викинги'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Ирландия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Япония')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жеребец'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Полиция Гавайев'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Столпы Земли'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Чудопад'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Чудопад'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Отчаянные домохозяйки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Родина'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Коварные горничные'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Кровь и песок'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Событие'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Непокорная Земля'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супергёрл'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гудини'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Друзья'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди Альфа'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Вояджер '), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенда об Искателе'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Шаннары'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Милдред Пирс'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Визитеры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На краю Вселенной'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Австралия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На краю Вселенной'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мистер Робот'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хранилище 13'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остров Харпера'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Убийство'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Утопия'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притворщик'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'И никого не стало'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город мечты'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черные паруса'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город хищниц'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенды'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Ирландия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '666 Парк авеню'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Футурама'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Энтерпрайз'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поворот'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Род человеческий'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лисица'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история преступлений'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Пробуждение'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поверхность'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ночной администратор'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ночной администратор'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'РеГенезис'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звездные врата: Вселенная'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская семейка'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сорвиголова'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В Филадельфии всегда солнечно'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мгновения грядущего'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Эврика'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Иерихон'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дневники вампира'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'От заката до рассвета'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек ниоткуда'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мушкетеры'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Великобритания')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Революция'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история ужасов'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шах и мат'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Смертельная битва: Наследие'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Смертельная битва: Наследие'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Канада')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ведьмы Ист-Энда'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мост'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доминион'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терра Нова'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терра Нова'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Австралия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шепот'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последователи'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Череп и кости'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'Англия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сыны анархии'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Путешественник'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Боги арены'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Штамм'), (SELECT CountryId FROM CountriesTb WHERE CountryName = 'США'));
