INSERT INTO TvGenreTb (SeriesId, GenreId) VALUES 
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Стрела'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Стрела'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Стрела'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жизнь после людей'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Документальный фильм')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жизнь после людей'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Постапокалиптика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Следующее поколение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Следующее поколение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Санта-Хрякус'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Санта-Хрякус'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одиссея 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одиссея 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одиссея 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В пустыне смерти'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В пустыне смерти'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В пустыне смерти'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Кошмары и фантазии Стивена Кинга '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Война и мир'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5 - Затерянные сказания'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Узник'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уилфред'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Биография')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Месть'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Борджиа'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Историческая драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новая Одиссея'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новая Одиссея'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Выжившие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Игра престолов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Игра престолов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевики')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Досье Дрездена'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агенты Щ.И.Т.'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агенты Щ.И.Т.'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агенты Щ.И.Т.'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город гангстеров'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город гангстеров'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город гангстеров'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Под куполом'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Под куполом'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мастера научной фантастики'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Космические рейнджеры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Космические рейнджеры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джекил'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дракула'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дракула'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Десница Божья'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Десница Божья'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новый день'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новый день'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Новый день'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сотня'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джонатан Стрендж и мистер Норрелл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джонатан Стрендж и мистер Норрелл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'История')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агент Картер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Шпионский боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агент Картер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Агент Картер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бойтесь ходячих мертвецов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бойтесь ходячих мертвецов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Компьютерщики'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Светлячок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Светлячок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Светлячок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Вестерн')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крайние меры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крайние меры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крайние меры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крайние меры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенды завтрашнего дня'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенды завтрашнего дня'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Падение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Падение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Нация Z'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Нация Z'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Нация Z'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Железный человек'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Каприка '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Научная фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Каприка '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сонная лощина'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сонная лощина'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мистика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Плащ'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Касл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Касл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Касл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джессика Джонс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джессика Джонс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джессика Джонс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Джессика Джонс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черный список'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черный список'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черный список'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Войны клонов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Космическая фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Войны клонов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вавилон 5'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Военный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Обмани меня'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Франкенштейна'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Франкенштейна'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На Тихом океане'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На Тихом океане'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Военный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мотель Бейтса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мотель Бейтса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мотель Бейтса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Орлиное сердце'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Колония'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата: Атлантида'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Красавица и чудовище'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Красавица и чудовище'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бульварные ужасы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Бульварные ужасы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Герои: Возрождение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Искусственный интеллект'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Искусственный интеллект'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Аквамен'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Аквамен'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Аквамен'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Аквамен'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Фарт'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Избранный'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Избранный'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Экшен')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лучше звоните Солу'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лучше звоните Солу'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лучше звоните Солу'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '11.22.63'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '11.22.63'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '11.22.63'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Глубокий космос 9'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Глубокий космос 9'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Глубокий космос 9'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Глубокий космос 9'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Забытые'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Забытые'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Константин'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Константин'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Первородные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мистика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Первородные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Перевозчик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супершторм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супершторм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супершторм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Острые козырьки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Острые козырьки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Почти человек'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Почти человек'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Почти человек'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Контакт'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Конец детства'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Конец детства'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Конец детства'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Салем'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Салем'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Салем'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притяжению вопреки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притяжению вопреки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Неизвестные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Неизвестные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флеминг: человек, который хотел стать Бондом'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флеминг: человек, который хотел стать Бондом'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Биография')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во плоти'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во плоти'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уэйуорд Пайнс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уэйуорд Пайнс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Уэйуорд Пайнс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди будущего'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди будущего'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Фильмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Фильмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Фильмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Врата'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Пропавшая комната'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Континуум'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Континуум'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Континуум'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доктор Хаус'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доктор Хаус'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клан Кеннеди'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клан Кеннеди'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Исторический')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последний корабль'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последний корабль'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последний корабль'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ходячие мертвецы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вечность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Вечность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Космос: Далёкие уголки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Верь'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Верь'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Слепое пятно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Слепое пятно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Слепое пятно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Таинственные знаки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мистика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Таинственные знаки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Киллджойс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Готэм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Готэм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Готэм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Демоны да Винчи'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Демоны да Винчи'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тайный круг'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тайный круг'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тайный круг'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Укушенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Укушенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Укушенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Темная материя'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Темная материя'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Темная материя'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спираль'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спираль'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рождение мафии: Нью-Йорк'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рождение мафии: Нью-Йорк'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рождение мафии: Нью-Йорк'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Алькатрас'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Алькатрас'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Алькатрас'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Святой дозор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Крик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Герои'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Герои'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Фарго'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Фарго'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Подозреваемый'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Подозреваемый'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мёртвые, как я'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мёртвые, как я'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во все тяжкие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во все тяжкие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Во все тяжкие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Восстание Техаса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Восстание Техаса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Вестерн')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '4400'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '4400'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '4400'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '4400'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шерлок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шерлок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мультфильм')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздные войны: Повстанцы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Библиотекари'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терминатор: Хроники Сары Коннор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терминатор: Хроники Сары Коннор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терминатор: Хроники Сары Коннор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Культ'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Культ'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Культ'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Барыги'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Барыги'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Быть человеком'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Быть человеком'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Быть человеком'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Области тьмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Области тьмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Области тьмы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Экспансия'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Экспансия'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сошедшие с небес'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Батл Крик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Батл Крик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Записки юного врача'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек в высоком замке'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек в высоком замке'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек в высоком замке'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Элементарно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Элементарно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Секретные материалы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Секретные материалы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Секретные материалы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Секретные материалы'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Декстер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Декстер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Декстер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Декстер'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Волшебники'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Волшебники'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Волшебники'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Волшебники'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Оригинальный'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Оригинальный'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '12 обезьян'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '12 обезьян'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '12 обезьян'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Квантовый скачок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Семейный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Квантовый скачок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Квантовый скачок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Квантовый скачок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Научная фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Клондайк'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Андромеда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Андромеда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Андромеда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флэш'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флэш'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флэш'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Флэш'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Живая мишень'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Живая мишень'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Живая мишень'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Живая мишень'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Исторический')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Рим'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Военный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ад на колесах'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ад на колесах'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Вестерн')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ребенок Розмари'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ребенок Розмари'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ребенок Розмари'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ребенок Розмари'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Минисериал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Калифорникейшн'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Калифорникейшн'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остаться в живых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остаться в живых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остаться в живых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остаться в живых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Изгои'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Изгои'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гримм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гримм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гримм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гримм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Управление гневом'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Викинги'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Викинги'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Исторический')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Викинги'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Анимационный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное: Аниме'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жеребец'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Жеребец'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Полиция Гавайев'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Столпы Земли'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Исторический')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Чудопад'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Чудопад'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Отчаянные домохозяйки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Отчаянные домохозяйки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Отчаянные домохозяйки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Отчаянные домохозяйки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Родина'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Коварные горничные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Коварные горничные'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Кровь и песок'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Историческая драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Событие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Биография')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Война проклятых'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Непокорная Земля'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Непокорная Земля'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Непокорная Земля'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супергёрл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супергёрл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Супергёрл'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гудини'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Гудини'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Биография')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Друзья'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Друзья'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди Альфа'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди Альфа'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди Альфа'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Люди Альфа'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Вояджер '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Вояджер '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Вояджер '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Вояджер '), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенда об Искателе'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенда об Искателе'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Одинокие стрелки'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Шаннары'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Шаннары'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хроники Шаннары'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Милдред Пирс'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Визитеры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Визитеры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На краю Вселенной'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На краю Вселенной'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'На краю Вселенной'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мистер Робот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мистер Робот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хранилище 13'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Хранилище 13'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остров Харпера'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остров Харпера'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Остров Харпера'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мистика триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Убийство'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Убийство'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Убийство'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Утопия'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Утопия'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притворщик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притворщик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притворщик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Притворщик'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'И никого не стало'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'И никого не стало'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'И никого не стало'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'И никого не стало'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город мечты'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город мечты'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город мечты'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черные паруса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Черные паруса'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Город хищниц'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Легенды'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Военный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Тюдоры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'История')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Камелот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Камелот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Камелот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Исторический')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = '666 Парк авеню'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мистика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Футурама'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Футурама'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Футурама'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мультфильм')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Энтерпрайз'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Энтерпрайз'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный путь: Энтерпрайз'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поворот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Род человеческий'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Род человеческий'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Род человеческий'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лисица'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мультфильм')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Лисица'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история преступлений'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история преступлений'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история преступлений'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Биография')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Пробуждение'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поверхность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поверхность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поверхность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Поверхность'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ночной администратор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ночной администратор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ночной администратор'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'РеГенезис'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'РеГенезис'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звездные врата: Вселенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звездные врата: Вселенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звездные врата: Вселенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звездные врата: Вселенная'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская семейка'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сорвиголова'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сорвиголова'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сорвиголова'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сверхъестественное'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'В Филадельфии всегда солнечно'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ситком')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мгновения грядущего'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мгновения грядущего'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'За гранью'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Эврика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Эврика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Комедия')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Иерихон'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Иерихон'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дневники вампира'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дневники вампира'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Дневники вампира'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'От заката до рассвета'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'От заката до рассвета'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'От заката до рассвета'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек ниоткуда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек ниоткуда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Человек ниоткуда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Река'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мушкетеры'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Революция'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Революция'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история ужасов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история ужасов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Американская история ужасов'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шах и мат'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Детектив')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шах и мат'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Смертельная битва: Наследие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Смертельная битва: Наследие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Смертельная битва: Наследие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ведьмы Ист-Энда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Ведьмы Ист-Энда'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мост'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мост'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Мост'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминал')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доминион'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доминион'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Доминион'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Экшен')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Терра Нова'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шепот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Шепот'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последователи'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последователи'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Криминальный')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Последователи'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Триллер')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Череп и кости'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Боевик')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Приключения')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Звёздный крейсер Галактика'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Сыны анархии'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Путешественник'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фэнтези')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Путешественник'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Мелодрама')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Воздействие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Воздействие'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Экшн')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Спартак: Боги арены'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Историческая драма')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Штамм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Ужасы')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Штамм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Фантастика')),
((SELECT SeriesId FROM TvSeriesTb WHERE SeriesName = 'Штамм'), (SELECT GenreId FROM GenresTb WHERE GenreName = 'Драма'));
